config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import LoginPage, RegistrationPage

app_name = 'users'

urlpatterns = [
    path('login', LoginPage.as_view(template_name='users/login.html'), name='login'),
    path('registration', RegistrationPage.as_view(template_name='users/registration.html'), name='registration'),
    path('logout', LogoutView.as_view(), name='logout'),
]

shop/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    email = models.EmailField(max_length=255, unique=True, verbose_name='адрес электронной почты')
    phone_number = models.CharField(max_length=11, unique=True, verbose_name='номер телефона')

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

shop/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    
    context = {
        'title' : 'TuneHub | Главная страница'
    }

    return render(request, 'index.html', context)

users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import LoginForm, RegisterForm
from users.models import User


# Create your views here.
class LoginPage(LoginView):
    form_class = LoginForm
    extra_context = {'title': 'TuneHub | Авторизация'}


class RegistrationPage(CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'TuneHub | Регистрация'}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
</head>
<body>
{% include 'includes/header.html' %}
{% block content %}

{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/includes/header.html
<nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'shop:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Каталог</a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">Корзина</a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">FAQ</a>
                </li>
            </ul>
        </div>

    </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container justify-content-center align-items-center">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3 text-center mt-2">
                <h1>Авторизация</h1>
                <form method="post" class="text-start">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary w-100">Войти</button>
                </form>
                <a href="{% url 'users:registration' %}" class="link-offset-1 mt-2">Нет аккаунта? Зарегистрируйтесь</a>
            </div>

        </div>
    </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}

{% block content %}
    <div class="container justify-content-center align-items-center">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3 text-center">
                <h1>Регистрация</h1>
                <form method="post" class="text-start">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary w-100">Зарегистрироваться</button>
                </form>
                <a href="{% url 'users:login' %}" class="link-offset-1">Есть аккаунт? Авторизуйтесь</a>
            </div>
        </div>
    </div>

{% endblock %}